/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyCard {
        "userName": string;
    }
    interface RatingComponent {
        "maxValue": number;
        "value": number;
    }
    interface SearchWorld {
        "inputText": any;
    }
}
declare global {
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    interface HTMLRatingComponentElement extends Components.RatingComponent, HTMLStencilElement {
    }
    var HTMLRatingComponentElement: {
        prototype: HTMLRatingComponentElement;
        new (): HTMLRatingComponentElement;
    };
    interface HTMLSearchWorldElement extends Components.SearchWorld, HTMLStencilElement {
    }
    var HTMLSearchWorldElement: {
        prototype: HTMLSearchWorldElement;
        new (): HTMLSearchWorldElement;
    };
    interface HTMLElementTagNameMap {
        "my-card": HTMLMyCardElement;
        "rating-component": HTMLRatingComponentElement;
        "search-world": HTMLSearchWorldElement;
    }
}
declare namespace LocalJSX {
    interface MyCard {
        "userName"?: string;
    }
    interface RatingComponent {
        "maxValue"?: number;
        "value"?: number;
    }
    interface SearchWorld {
        "inputText"?: any;
    }
    interface IntrinsicElements {
        "my-card": MyCard;
        "rating-component": RatingComponent;
        "search-world": SearchWorld;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-card": LocalJSX.MyCard & JSXBase.HTMLAttributes<HTMLMyCardElement>;
            "rating-component": LocalJSX.RatingComponent & JSXBase.HTMLAttributes<HTMLRatingComponentElement>;
            "search-world": LocalJSX.SearchWorld & JSXBase.HTMLAttributes<HTMLSearchWorldElement>;
        }
    }
}
